###############################################################################
# ABC-Technologies
# Host Variables
#
# Host : k8s-master
#
# Purpose:
# Configuration specific to the Kubernetes Control Plane.
#
###############################################################################

###############################################################################
# Kubernetes Control Plane
###############################################################################

control_plane: true

###############################################################################
# kubectl
###############################################################################

kubectl_binary: /usr/bin/kubectl

###############################################################################
# kubeconfig
###############################################################################

kubeconfig: /home/bharat/.kube/config

###############################################################################
# Kubernetes API Server
###############################################################################

api_server: "https://192.168.56.10:6443"

###############################################################################
# SSH User
###############################################################################

ssh_user: bharat

###############################################################################
# Workspace
###############################################################################

workspace: "/home/bharat/ABC-Technologies"

###############################################################################
# Kubernetes Manifest Directory
###############################################################################

manifest_directory: "{{ workspace }}/kubernetes"

###############################################################################
# Temporary Directory
###############################################################################

tmp_directory: "/tmp/abc-technologies"

###############################################################################
# kubectl Timeout
###############################################################################

kubectl_timeout: 180s