apiVersion: networking.k8s.io/v1
kind: NetworkPolicy

metadata:
  name: abc-technologies-network-policy
  namespace: abc-technologies

spec:

  podSelector:

    matchLabels:
      app: abc-technologies

  policyTypes:
    - Ingress
    - Egress

###############################################################################
# INGRESS
###############################################################################

  ingress:

  #
  # Allow traffic from pods in the same namespace
  #
  - from:

      - podSelector: {}

  #
  # Allow traffic from NGINX Ingress Controller
  #
  - from:

      - namespaceSelector:

          matchLabels:
            kubernetes.io/metadata.name: platform

  #
  # Allow traffic from Istio
  #
  - from:

      - namespaceSelector:

          matchLabels:
            kubernetes.io/metadata.name: istio-system

  #
  # Allow Prometheus scraping
  #
  - from:

      - namespaceSelector:

          matchLabels:
            kubernetes.io/metadata.name: monitoring

    ports:

      - protocol: TCP

        port: 8080

###############################################################################
# EGRESS
###############################################################################

  egress:

  #
  # Allow DNS
  #
  - to:

      - namespaceSelector: {}

    ports:

      - protocol: UDP

        port: 53

      - protocol: TCP

        port: 53

  #
  # Allow HTTPS
  #
  - ports:

      - protocol: TCP

        port: 443

  #
  # Allow HTTP
  #
  - ports:

      - protocol: TCP

        port: 80

  #
  # Allow Prometheus Metrics
  #
  - to:

      - namespaceSelector:

          matchLabels:
            kubernetes.io/metadata.name: monitoring