apiVersion: v1
kind: ServiceAccount

metadata:
  name: abc-technologies-sa
  namespace: abc-technologies

  labels:
    app: abc-technologies
    environment: production

automountServiceAccountToken: false