###############################################################################
# ABC-Technologies
# Ansible Inventory
#
# Project : ABC-Technologies
# Author  : Bharat Dasa
#
# Purpose:
# Defines the target infrastructure for deployment.
#
# NOTE:
# We deploy applications to Kubernetes through the Control Plane.
# Worker nodes are managed by Kubernetes Scheduler.
#
###############################################################################

###############################################################################
# Kubernetes Control Plane
###############################################################################

[kubernetes_master]

k8s-master ansible_host=192.168.56.10 ansible_user=bharat ansible_python_interpreter=/usr/bin/python3

###############################################################################
# Kubernetes Cluster
###############################################################################

[kubernetes_cluster:children]

kubernetes_master

###############################################################################
# Global Variables
###############################################################################

[kubernetes_cluster:vars]

###############################################################################
# SSH
###############################################################################

ansible_connection=ssh

ansible_become=true
ansible_become_method=sudo

###############################################################################
# SSH Options
###############################################################################

ansible_ssh_common_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'

###############################################################################
# SSH Private Key
#
# Jenkins injects the SSH key automatically.
# Uncomment only when running manually.
###############################################################################

# ansible_ssh_private_key_file=~/.ssh/id_rsa